In [1]:
import pandas as pd
import numpy as np 


df1=pd.read_csv("/home/saidharahas/jupyter_projects/anime_reco/anime_data/anime.csv")
df2=pd.read_csv("/home/saidharahas/jupyter_projects/anime_reco/anime_data/rating.csv")
df1.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [3]:
df2.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [2]:
from collections import defaultdict

genre=set()
gen_counts=defaultdict(int)
for i in df1["genre"]:
      j=str(i).split(',')
      for k in j:
            genre.add(k.strip())
            gen_counts[k.strip()]+=1
genre=list(genre)
genre.sort()
for i in genre:
       print(i)

Action
Adventure
Cars
Comedy
Dementia
Demons
Drama
Ecchi
Fantasy
Game
Harem
Hentai
Historical
Horror
Josei
Kids
Magic
Martial Arts
Mecha
Military
Music
Mystery
Parody
Police
Psychological
Romance
Samurai
School
Sci-Fi
Seinen
Shoujo
Shoujo Ai
Shounen
Shounen Ai
Slice of Life
Space
Sports
Super Power
Supernatural
Thriller
Vampire
Yaoi
Yuri
nan

In [30]:
print(gen_counts)

defaultdict(<class 'int'>, {'Drama': 2016, 'Romance': 1464, 'School': 1220, 'Supernatural': 1037, 'Action': 2845, 'Adventure': 2348, 'Fantasy': 2309, 'Magic': 778, 'Military': 426, 'Shounen': 1712, 'Comedy': 4645, 'Historical': 806, 'Parody': 408, 'Samurai': 148, 'Sci-Fi': 2070, 'Thriller': 87, 'Sports': 543, 'Super Power': 465, 'Space': 381, 'Slice of Life': 1220, 'Mecha': 944, 'Music': 860, 'Mystery': 495, 'Seinen': 547, 'Martial Arts': 265, 'Vampire': 102, 'Shoujo': 603, 'Horror': 369, 'Police': 197, 'Psychological': 229, 'Demons': 294, 'Ecchi': 637, 'Josei': 54, 'Shounen Ai': 65, 'Game': 181, 'Dementia': 240, 'Harem': 317, 'Cars': 72, 'Kids': 1609, 'Shoujo Ai': 55, 'nan': 62, 'Hentai': 1141, 'Yaoi': 39, 'Yuri': 42})

In [20]:
df1.shape

(12294, 7)

In [21]:
df2.shape

(7813737, 3)

In [35]:
for i in genre:
     val=list()
     for j in df1['genre']:
          words=str(j).split(',')
          for k in words:
               k.strip()
          if i in words:
              val.append(1)
          else:
              val.append(0)
     df1[i]=val

In [39]:
df1.head()

,anime_id,name,genre,type,episodes,rating,members,Action,Adventure,Cars,...,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri,nan
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
print(df1.shape)
print(df2.shape)

(12294, 7)
(7813737, 3)

In [5]:
from scipy.sparse import csr_matrix

users = df2["user_id"].astype("category").cat.codes
anime = df2["anime_id"].astype("category").cat.codes

mat = csr_matrix(
    (df2["rating"], (users, anime))
)

In [12]:
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
df2 = df2[df2["rating"] > 0]
users = df2["user_id"].astype("category").cat.codes
anime = df2["anime_id"].astype("category").cat.codes

mat = csr_matrix(
    (df2["rating"], (users, anime))
)

svd = TruncatedSVD(n_components=50)

U = svd.fit_transform(mat)
V = svd.components_

print(U.shape)
print(V.shape)

(69600, 50)
(50, 9927)

In [13]:
print(U[:5])      
print(V[:, :5])

[[ 2.99235736e+00 -2.22748563e+00  4.39325718e-01  3.50442678e+00
  -1.02678873e+00  2.43780030e+00  1.16620551e+00  7.13140743e-01
  -2.83710191e+00 -1.04752020e+00  1.38240222e+00  9.63353188e-01
  -1.77529822e+00 -1.37495047e+00 -1.35682619e+00 -3.63217470e-01
   1.29962233e+00 -1.47695095e+00  1.07284615e+00  3.27680731e+00
  -3.09033177e+00  9.12116259e-01  1.10037649e+00  9.92112797e-01
  -4.75777097e-01 -7.93484786e-01 -3.42529567e-02 -1.24048914e-01
   7.32591136e-01  1.50664646e+00  3.02507454e-01 -8.72674508e-01
  -1.09199842e+00  2.53796372e+00 -2.08816601e+00 -1.35617384e+00
   3.43275545e-01 -1.51069774e+00  2.19982596e+00  1.50652811e+00
   7.74671901e-01 -5.43037082e-01  1.17595036e+00 -1.25045760e+00
   6.56030198e-01  7.30821424e-01  1.09156276e+00  4.55121880e-01
   3.87877470e+00 -8.47323532e-01]
 [ 4.93187149e-01 -2.82821388e-01  7.61715507e-01  4.69778263e-01
   6.00704625e-01 -3.98392094e-01 -4.56941205e-01 -5.56746570e-01
   6.58917107e-01 -8.00170559e-01 -2.37441771e-01  3.78731807e-01
  -3.53066021e-01 -5.34454672e-01 -6.73330146e-01  4.02849275e-01
   9.63073695e-01  1.07379763e-01 -1.58307328e-01 -1.19432632e-01
   1.24439976e-01 -3.67005932e-02 -1.57516266e+00  7.73784812e-01
  -5.29672021e-01  4.83971777e-01  1.37822626e+00  4.89927835e-01
   3.98419452e-01  3.49453880e-01  5.86149684e-01 -5.76428689e-01
   1.08582585e+00  9.67925369e-01  2.93775637e-01  1.12921451e-01
   7.78890874e-01  3.29518202e-02  4.07764487e-01  8.90613518e-01
   1.06237093e+00  7.71805097e-01  1.04464079e-01 -3.42161457e-01
  -1.79508139e-01  1.39782272e+00  4.68858932e-01 -5.02131386e-02
  -8.82439301e-01  3.97963633e-01]
 [ 2.65215285e+01 -8.92340743e+00  2.33622166e+01  1.13680124e+01
  -2.99050864e+00 -6.12739846e+00  6.82599970e+00 -2.26972198e+00
   3.47398199e+00 -1.84537804e+00  3.73403597e+00 -3.40671606e+00
  -5.78270797e+00 -1.49754917e+01 -1.93914738e+00  2.01858380e+00
  -6.82119666e+00 -1.62786040e+00 -4.43306420e+00 -3.04187547e+00
  -4.24919217e+00 -1.19432285e+00  1.29624105e+00  1.48255432e+01
   1.86802677e+00  7.80132931e-01  7.83247416e+00  2.16920695e+00
   5.98271312e+00  2.48487133e+00  9.57460202e-01 -1.58035385e+00
  -5.10893343e-01  1.40130536e+00  3.77699628e+00 -2.48882897e+00
   1.56470663e+00 -7.66913907e-01 -2.21082264e+00 -1.49657791e+00
   4.00349625e+00  2.35482500e+00 -5.94886186e+00 -1.15247099e+00
  -3.62653624e+00  2.57680932e+00  2.12309572e-01 -3.06799430e+00
  -2.45852411e+00  3.49526034e+00]
 [ 4.62653226e+01 -9.12207303e+00  3.60019970e-01 -4.62940606e+00
  -4.94452296e+00 -1.70356069e+01  9.30849383e+00 -1.19752988e+01
   1.42422932e+01 -2.27265320e+01 -8.79214854e+00  9.04944628e+00
  -6.22736627e-01 -6.30860725e-01  6.24388730e+00  4.93539343e+00
  -5.23417766e+00 -7.34842885e+00  6.53524473e+00 -1.21444775e+01
  -2.57573079e+00 -8.81274242e+00 -2.85659999e+00  5.85083008e+00
  -3.69644327e+00 -6.35238583e+00  2.33278314e+00 -4.20967731e+00
   7.11787303e-01  3.12594189e+00 -5.76281570e-01  1.31393091e-01
  -1.11702440e+01 -3.01219198e+00 -3.17493082e+00  7.06120138e+00
   1.14781085e+00  1.16378358e+00 -1.69733275e+00 -7.64355683e+00
  -5.69496387e+00 -1.46095847e+00  1.31940530e-01  3.20687844e+00
   1.90196642e+00  3.48818628e+00 -6.04009739e+00  1.50205215e+00
  -8.86831901e-01 -4.38780298e+00]
 [ 5.70332801e+01 -2.54100205e+01 -1.73334158e+01 -4.13701097e+00
  -1.33817102e+01 -5.26118206e+00  3.07129146e+01  6.37798078e+00
  -1.43415154e+00  1.77689771e+01 -1.54492842e+01 -2.67475305e+00
  -1.03122084e+00  1.18985103e+01  1.06274998e+00  1.63478897e+01
   6.00563391e+00 -6.05229129e+00  1.19072250e+01  5.34662136e+00
  -4.50769665e+00 -9.28965438e+00 -1.29157779e+01  1.10901481e+01
   1.89685804e+00  4.49732307e+00 -1.36837341e+01 -8.42092589e+00
   3.63900510e+00 -7.95810689e+00 -3.92032206e+00  1.19949760e+00
  -2.52342554e-01  6.38427715e-01 -1.07947777e+01 -1.32371047e+00
   2.68458595e+00  2.43389571e+00 -4.05242042e+00 -7.99016946e+00
   2.16370698e+00  9.95148979e+00  1.04849318e+00  9.40212395e+00
   2.53937914e+00 -6.92409938e-01  2.19500661e+00 -1.72926203e+00
   3.97908547e+00  9.86504661e-01]]
[[ 6.06480380e-02  2.73391326e-02  4.36845690e-02  1.02647998e-02
   1.77357206e-03]
 [ 1.00049382e-01  6.15359522e-02  7.48400963e-02  2.69543024e-02
   2.79605294e-03]
 [ 4.73188054e-02  1.21143669e-02  8.32574715e-03 -6.74584479e-03
  -3.68332651e-03]
 [-4.43565948e-02 -4.17474787e-02  6.53836036e-03 -2.85282704e-03
   3.43043730e-03]
 [-1.15615544e-01 -6.09647611e-02 -7.84417136e-02 -1.13173117e-02
  -1.59513898e-03]
 [ 1.95312081e-02 -1.47684165e-02 -2.04090365e-02 -2.30466508e-02
  -7.02663894e-03]
 [ 1.12435794e-02  2.35517160e-02 -7.56016250e-03 -7.95416402e-03
  -1.72790184e-03]
 [ 5.78419121e-02  2.51765705e-02  3.96865845e-02  2.18637865e-02
   5.71744345e-05]
 [-2.62043051e-02 -3.54150855e-02 -1.54351779e-02 -1.71237712e-02
   3.58822220e-03]
 [-1.03666121e-01 -5.11919266e-02 -7.30229055e-02 -2.96557632e-03
  -2.69271203e-03]
 [-1.03732125e-01 -1.57765482e-02 -8.57262017e-02 -7.43949577e-03
  -3.54926228e-03]
 [ 1.62070270e-02  9.99178263e-03  1.26561888e-02 -9.66818750e-03
  -3.20245407e-03]
 [-1.34330871e-02 -1.32819252e-02 -1.81031505e-02 -2.72527641e-02
  -4.47800022e-03]
 [ 8.26673832e-02  5.29277252e-02  4.97692351e-02  1.61266148e-02
  -4.62872813e-03]
 [ 5.87790505e-03 -2.23518963e-02  2.89402804e-03 -9.68910958e-03
  -3.62247967e-03]
 [-5.23083706e-02 -3.69098380e-02 -6.39483603e-02 -1.98773936e-02
   8.74195589e-04]
 [ 4.20753033e-02  3.97699605e-02 -1.26853485e-03 -8.34892994e-03
  -2.33428407e-03]
 [ 7.95872202e-02  3.39859082e-02  3.85591512e-02 -1.26761906e-02
  -2.10841108e-03]
 [ 5.82179694e-02  3.79088616e-02  7.86840124e-02  1.96121444e-02
   3.56344144e-03]
 [ 4.20215531e-02  1.37057516e-02  1.95746918e-02  1.36488268e-03
  -9.09336119e-04]
 [ 5.38299130e-02  4.94892513e-03  4.43863591e-02 -9.37046991e-03
  -1.39732229e-03]
 [-3.21367289e-02  5.86864308e-03 -2.35325985e-02  2.77397806e-03
  -3.55584440e-03]
 [ 4.12273103e-02  1.30227602e-02  3.14856039e-02  9.89248368e-03
   7.33075192e-04]
 [ 2.11968503e-02  6.65504491e-03  1.44649427e-03 -1.18964110e-02
  -7.45895853e-03]
 [-9.17115583e-03  8.13333175e-03  5.33828547e-03 -6.03556883e-03
  -3.98071525e-03]
 [ 1.27668444e-03  1.96390743e-02 -8.25798353e-03  1.50926223e-02
  -7.51244730e-04]
 [ 3.39479333e-02  4.12599775e-02  4.16823469e-02  1.67282560e-02
  -1.71128845e-03]
 [ 1.30080437e-01  7.01432327e-02  4.65124904e-02  1.95552373e-02
  -7.24092865e-03]
 [ 3.85194009e-03 -2.55156977e-03 -3.71265881e-02 -1.67143950e-02
  -7.23921032e-03]
 [-6.30798710e-02 -3.54659690e-02 -1.91872830e-02 -7.95638722e-04
   5.73463587e-03]
 [-4.37588534e-02 -1.03012195e-02  1.37038310e-02 -6.11372857e-03
  -5.93172066e-03]
 [ 7.97703757e-02  4.45783155e-02  2.30147947e-02 -3.11085919e-03
  -1.68415792e-03]
 [ 1.27105231e-01  4.76259473e-02  2.29165655e-02  1.25197732e-02
   5.68697888e-04]
 [ 5.33121379e-02  3.50369222e-03  2.32000548e-02 -3.20634462e-04
   1.85972265e-03]
 [ 4.09819943e-02  3.28887658e-02  1.12128445e-03  1.04956155e-02
   3.92853623e-03]
 [ 1.54584390e-01  6.22332481e-02  5.83979815e-02  7.66353634e-03
   4.41440422e-03]
 [-1.35064335e-02 -1.24427331e-02  2.31736305e-02  4.02606634e-03
   2.05226937e-03]
 [-7.33379615e-02 -6.36502807e-04 -1.57417522e-02  6.00753395e-03
  -2.01336514e-03]
 [-5.15117277e-02 -6.13019588e-03 -6.10564334e-02  1.35462267e-02
   1.00102249e-03]
 [-6.98496288e-02 -2.98257218e-02 -5.81729897e-02 -1.70479834e-02
  -3.08946840e-03]
 [ 6.45025003e-02  2.22044305e-02  3.83857174e-02  9.19683273e-03
  -8.73564637e-04]
 [-1.33958505e-01 -5.35560637e-02 -9.08179791e-02  7.10924550e-03
   1.92357689e-04]
 [ 8.49020919e-02  3.52515621e-02  3.61496538e-02 -1.08626396e-02
   3.83387328e-03]
 [ 1.17201475e-02  9.62584833e-03  1.79151976e-02 -1.88020879e-02
   1.59120562e-03]
 [-1.21731595e-02 -2.33157304e-02 -2.75643994e-02  1.49136217e-03
  -2.03816056e-03]
 [ 1.23428682e-02  9.24590380e-03  1.69389268e-02  4.05780015e-03
  -3.52811421e-04]
 [ 8.07057214e-02  2.96706947e-02  2.44513472e-02  1.22625960e-02
  -4.80287453e-03]
 [-7.13278085e-03 -2.43986576e-02  1.01266581e-02 -7.37919123e-04
   3.28991753e-03]
 [-1.16526568e-02  1.21295180e-02 -2.95407156e-03  4.90816884e-03
  -3.25362160e-03]
 [ 6.12622931e-02  1.89391440e-02  3.25869411e-03  1.75699850e-02
  -4.10025446e-04]]

In [14]:
i=41
j=20

pred = U[i] @ V[:, j]

print(pred)

-0.22676285971059082

In [16]:
from sklearn.decomposition import NMF 
nmf = NMF(
    n_components=50,
    init="random",
    random_state=42,
    max_iter=500
)
W = nmf.fit_transform(mat)
H = nmf.components_

print(W.shape)
print(H.shape)
i=41
j=20

pred = W[i] @ H[:, j]

print(pred)

(69600, 50)
(50, 9927)
0.0

In [17]:
i=40
j=20

pred = W[i] @ H[:, j]

print(pred)

0.7442605111151966

In [18]:
i=41
j=28

pred = W[i] @ H[:, j]

print(pred)

0.010302349130384941

In [ ]:
def grad_step(i, j, lr):
    
      for epoch in range(100):
    
        for row in df2.itertuples():
    
            i = row.user_id
            j = row.anime_id
            r = row.rating
    
            pred = W[i] @ H[:, j]
    
            err = r - pred
    
            old_w = W[i].copy()
    
            W[i] += lr * err * H[:, j]
    
            H[:, j] += lr * err * old_w
            print("OLD W:")
            print(old_w)
        
            print("\nNEW W:")
            print(W[i])
        
            print("\nCHANGE IN W:")
            print(W[i] - old_w)
        
            print("\nOLD H:")
            print(old_h)
        
            print("\nNEW H:")
            print(H[:, j])
        
            print("\nCHANGE IN H:")
            print(H[:, j] - old_h)
        
            print("\nPrediction:", pred)
            print("Error:", err)

In [ ]:
grad_step(41,28,0.0005)

In [27]:
df2["user_id"] = (
    df2["user_id"]
    .astype("category")
    .cat.codes
)

df2["anime_id"] = (
    df2["anime_id"]
    .astype("category")
    .cat.codes
)
num_users = df2["user_id"].nunique()
num_items = df2["anime_id"].nunique()

k = 50

W = np.random.normal(0, 0.1, (num_users, k))
H = np.random.normal(0, 0.1, (k, num_items))

In [31]:
import numpy as np
import pandas as pd

# -----------------------------------
# SMALL SAMPLE
# -----------------------------------

small_df = df2.sample(2000, random_state=42).copy()

# remove invalid ratings if needed
small_df = small_df[small_df["rating"] > 0]

# -----------------------------------
# CREATE COMPACT INDICES
# -----------------------------------

small_df["user_idx"] = (
    small_df["user_id"]
    .astype("category")
    .cat.codes
)

small_df["anime_idx"] = (
    small_df["anime_id"]
    .astype("category")
    .cat.codes
)

# -----------------------------------
# MATRIX DIMENSIONS
# -----------------------------------

num_users = small_df["user_idx"].nunique()
num_items = small_df["anime_idx"].nunique()

k = 10  # latent factors

# -----------------------------------
# INITIALIZE LATENT MATRICES
# -----------------------------------

W = np.random.normal(0, 0.01, (num_users, k))
H = np.random.normal(0, 0.01, (k, num_items))

# -----------------------------------
# TRAINING PARAMETERS
# -----------------------------------

lr = 0.05
reg = 0.02
epochs = 100

# -----------------------------------
# SGD TRAINING
# -----------------------------------

for epoch in range(epochs):

    total_err = 0

    for row in small_df.itertuples():

        i = row.user_idx
        j = row.anime_idx
        r = row.rating

        # prediction
        pred = W[i] @ H[:, j]

        # error
        err = r - pred

        # accumulate squared error
        total_err += err * err

        # save old user vector
        old_w = W[i].copy()

        # gradient updates
        W[i] += lr * (err * H[:, j] - reg * W[i])

        H[:, j] += lr * (err * old_w - reg * H[:, j])

    print(f"Epoch {epoch + 1}")
    print("Loss:", total_err)
    print("-" * 30)

# -----------------------------------
# TEST PREDICTION
# -----------------------------------

test_user = 0
test_item = 0

pred_rating = W[test_user] @ H[:, test_item]

print("Predicted Rating:", pred_rating)

Epoch 1
Loss: 126884.87039746053
------------------------------
Epoch 2
Loss: 126851.6787285277
------------------------------
Epoch 3
Loss: 126742.34856482936
------------------------------
Epoch 4
Loss: 126150.93313538963
------------------------------
Epoch 5
Loss: 123204.38509563415
------------------------------
Epoch 6
Loss: 115946.65098151487
------------------------------
Epoch 7
Loss: 104333.71797353875
------------------------------
Epoch 8
Loss: 89833.12215780061
------------------------------
Epoch 9
Loss: 74512.78430747864
------------------------------
Epoch 10
Loss: 60010.05304224743
------------------------------
Epoch 11
Loss: 47140.97185598446
------------------------------
Epoch 12
Loss: 36396.36049706199
------------------------------
Epoch 13
Loss: 27275.034191656272
------------------------------
Epoch 14
Loss: 19435.92408128845
------------------------------
Epoch 15
Loss: 13092.330144976902
------------------------------
Epoch 16
Loss: 8363.40722544771
------------------------------
Epoch 17
Loss: 5106.995889194939
------------------------------
Epoch 18
Loss: 3035.0828028999467
------------------------------
Epoch 19
Loss: 1815.5089641727627
------------------------------
Epoch 20
Loss: 1118.4577887620078
------------------------------
Epoch 21
Loss: 706.7718034321516
------------------------------
Epoch 22
Loss: 453.0475999025819
------------------------------
Epoch 23
Loss: 293.83219285842233
------------------------------
Epoch 24
Loss: 194.6453868433583
------------------------------
Epoch 25
Loss: 134.0373256710276
------------------------------
Epoch 26
Loss: 97.10584629161762
------------------------------
Epoch 27
Loss: 73.86728723284587
------------------------------
Epoch 28
Loss: 58.369124854369126
------------------------------
Epoch 29
Loss: 47.2808861977243
------------------------------
Epoch 30
Loss: 38.7181360135775
------------------------------
Epoch 31
Loss: 31.640169179240107
------------------------------
Epoch 32
Loss: 25.568806983678112
------------------------------
Epoch 33
Loss: 20.377166215712826
------------------------------
Epoch 34
Loss: 16.089329215172977
------------------------------
Epoch 35
Loss: 12.726986641057843
------------------------------
Epoch 36
Loss: 10.234215299980594
------------------------------
Epoch 37
Loss: 8.475310766784911
------------------------------
Epoch 38
Loss: 7.273801350344284
------------------------------
Epoch 39
Loss: 6.456875266623477
------------------------------
Epoch 40
Loss: 5.8837549798250555
------------------------------
Epoch 41
Loss: 5.454432633368324
------------------------------
Epoch 42
Loss: 5.1054148092002185
------------------------------
Epoch 43
Loss: 4.800487866590674
------------------------------
Epoch 44
Loss: 4.521572187513227
------------------------------
Epoch 45
Loss: 4.261599471047043
------------------------------
Epoch 46
Loss: 4.0195475774931895
------------------------------
Epoch 47
Loss: 3.7971498378639517
------------------------------
Epoch 48
Loss: 3.5967820236839088
------------------------------
Epoch 49
Loss: 3.420190500765689
------------------------------
Epoch 50
Loss: 3.26785793758929
------------------------------
Epoch 51
Loss: 3.138858888044448
------------------------------
Epoch 52
Loss: 3.031060141461832
------------------------------
Epoch 53
Loss: 2.941512571573755
------------------------------
Epoch 54
Loss: 2.8668924188346225
------------------------------
Epoch 55
Loss: 2.803886602678635
------------------------------
Epoch 56
Loss: 2.749466415092182
------------------------------
Epoch 57
Loss: 2.7010394675727905
------------------------------
Epoch 58
Loss: 2.656499730964433
------------------------------
Epoch 59
Loss: 2.6142079089376913
------------------------------
Epoch 60
Loss: 2.5729337003752337
------------------------------
Epoch 61
Loss: 2.531784141776176
------------------------------
Epoch 62
Loss: 2.4901333453178935
------------------------------
Epoch 63
Loss: 2.4475614459126698
------------------------------
Epoch 64
Loss: 2.4038054010076673
------------------------------
Epoch 65
Loss: 2.3587212934968362
------------------------------
Epoch 66
Loss: 2.3122563885831506
------------------------------
Epoch 67
Loss: 2.2644287847705136
------------------------------
Epoch 68
Loss: 2.215312612678704
------------------------------
Epoch 69
Loss: 2.1650270727995147
------------------------------
Epoch 70
Loss: 2.1137279957045547
------------------------------
Epoch 71
Loss: 2.061600973510238
------------------------------
Epoch 72
Loss: 2.0088554176545648
------------------------------
Epoch 73
Loss: 1.9557191386721748
------------------------------
Epoch 74
Loss: 1.9024332230565604
------------------------------
Epoch 75
Loss: 1.8492471085402788
------------------------------
Epoch 76
Loss: 1.7964138409374826
------------------------------
Epoch 77
Loss: 1.7441855416522911
------------------------------
Epoch 78
Loss: 1.6928091335054003
------------------------------
Epoch 79
Loss: 1.6425223721060795
------------------------------
Epoch 80
Loss: 1.5935502188537538
------------------------------
Epoch 81
Loss: 1.5461015773549667
------------------------------
Epoch 82
Loss: 1.50036640369633
------------------------------
Epoch 83
Loss: 1.456513196533258
------------------------------
Epoch 84
Loss: 1.4146868765674867
------------------------------
Epoch 85
Loss: 1.3750070752296213
------------------------------
Epoch 86
Loss: 1.3375668656216086
------------------------------
Epoch 87
Loss: 1.3024319801935926
------------------------------
Epoch 88
Loss: 1.2696405644706337
------------------------------
Epoch 89
Loss: 1.2392035108965642
------------------------------
Epoch 90
Loss: 1.211105400138338
------------------------------
Epoch 91
Loss: 1.1853060500766779
------------------------------
Epoch 92
Loss: 1.1617426385176304
------------------------------
Epoch 93
Loss: 1.1403323292202827
------------------------------
Epoch 94
Loss: 1.120975297463251
------------------------------
Epoch 95
Loss: 1.1035580258136597
------------------------------
Epoch 96
Loss: 1.087956726357804
------------------------------
Epoch 97
Loss: 1.0740407438565465
------------------------------
Epoch 98
Loss: 1.0616758046187649
------------------------------
Epoch 99
Loss: 1.050726996238133
------------------------------
Epoch 100
Loss: 1.0410613905467347
------------------------------
Predicted Rating: -6.076800255502957